# **Single Channel Conv2D from Scratch**# 

In [2]:
import numpy as np

class Conv2D:

    def __init__(self, kernel_size, stride=1, padding=0):

        self.kernel_size = kernel_size
        self.stride = stride
        self.padding = padding

        self.kernel = np.random.randn(
            kernel_size,
            kernel_size
        )

    def add_padding(self, x):

        if self.padding == 0:
            return x

        return np.pad(
            x,
            (
                (self.padding, self.padding),
                (self.padding, self.padding)
            ),
            mode='constant'
        )

    def forward(self, x):

        x = self.add_padding(x)

        h, w = x.shape

        out_h = (
            (h - self.kernel_size) // self.stride
        ) + 1

        out_w = (
            (w - self.kernel_size) // self.stride
        ) + 1

        output = np.zeros((out_h, out_w))

        for i in range(out_h):

            for j in range(out_w):

                h_start = i * self.stride
                h_end = h_start + self.kernel_size

                w_start = j * self.stride
                w_end = w_start + self.kernel_size

                region = x[
                    h_start:h_end,
                    w_start:w_end
                ]

                output[i, j] = np.sum(
                    region * self.kernel
                )

        return output


# Example Input
x = np.array([
    [1, 2, 3, 0],
    [0, 1, 2, 3],
    [3, 0, 1, 2],
    [2, 3, 0, 1]
])

conv = Conv2D(
    kernel_size=3,
    stride=1,
    padding=1
)

output = conv.forward(x)

print("Kernel:")
print(conv.kernel)

print("\nOutput:")
print(output)

Kernel:
[[-1.15895309  2.05149213 -0.36040871]
 [-1.34292169  1.4949381  -0.84656695]
 [ 0.52848444  0.4233263  -0.1406446 ]]

Output:
[[-0.3388404  -0.75070924  2.75217415 -1.70181728]
 [ 1.75408666  3.10941796  3.08586096 -0.30275131]
 [ 4.54912437 -1.21770952  3.10941796  5.906851  ]
 [ 6.60465174 -2.03829707 -3.54465731  4.43896926]]


# **Multi-Channel Conv2D From Scratch**

In [5]:
import numpy as np

class Conv2D:

    def __init__(
        self,
        in_channels,
        out_channels,
        kernel_size,
        stride=1,
        padding=0
    ):

        self.in_channels = in_channels
        self.out_channels = out_channels
        self.kernel_size = kernel_size
        self.stride = stride
        self.padding = padding

        self.kernels = np.random.randn(
            out_channels,
            in_channels,
            kernel_size,
            kernel_size
        )

    def add_padding(self, x):

        if self.padding == 0:
            return x

        return np.pad(
            x,
            (
                (0, 0),
                (self.padding, self.padding),
                (self.padding, self.padding)
            ),
            mode='constant'
        )

    def forward(self, x):

        x = self.add_padding(x)

        C, H, W = x.shape

        out_h = (
            (H - self.kernel_size) // self.stride
        ) + 1

        out_w = (
            (W - self.kernel_size) // self.stride
        ) + 1

        output = np.zeros((
            self.out_channels,
            out_h,
            out_w
        ))

        for oc in range(self.out_channels):

            for i in range(out_h):

                for j in range(out_w):

                    h_start = i * self.stride
                    h_end = h_start + self.kernel_size

                    w_start = j * self.stride
                    w_end = w_start + self.kernel_size

                    region = x[
                        :,
                        h_start:h_end,
                        w_start:w_end
                    ]

                    output[oc, i, j] = np.sum(
                        region * self.kernels[oc]
                    )

        return output


# Example
x = np.random.randn(3, 5, 5)

conv = Conv2D(
    in_channels=3,
    out_channels=2,
    kernel_size=3,
    stride=1,
    padding=1
)

output = conv.forward(x)

print(output.shape)

(2, 5, 5)


# **PyTorch Equivalent**

In [6]:
import torch
import torch.nn as nn

conv = nn.Conv2d(
    in_channels=3,
    out_channels=16,
    kernel_size=3,
    stride=1,
    padding=1
)

x = torch.randn(1, 3, 224, 224)

out = conv(x)

print(out.shape)

torch.Size([1, 16, 224, 224])
